<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return apply_filters( 'wc_pandapay_settings',
	array(
		'enabled' => array(
			'title'       => __( 'Enable/Disable', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Enable Panda Pay', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => '',
			'default'     => 'no',
		),
		'testmode' => array(
			'title'       => __( 'Test mode', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Enable Test Mode', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'Place the payment gateway in test mode using test API keys.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'yes',
			'desc_tip'    => true,
		),
		'title' => array(
			'title'       => __( 'Title', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'This controls the title which the user sees during checkout.', 'woocommerce-gateway-pandapay' ),
			'default'     => __( 'Credit Card (Panda Pay)', 'woocommerce-gateway-pandapay' ),
			'desc_tip'    => true,
		),
		'description' => array(
			'title'       => __( 'Description', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'This controls the description which the user sees during checkout.', 'woocommerce-gateway-pandapay' ),
			'default'     => __( 'Pay with your credit card via Panda Pay.', 'woocommerce-gateway-pandapay' ),
			'desc_tip'    => true,
		),
		'test_publishable_key' => array(
			'title'       => __( 'Test Publishable Key', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'Get your API keys from your pandapay account.', 'woocommerce-gateway-pandapay' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'test_secret_key' => array(
			'title'       => __( 'Test Secret Key', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'Get your API keys from your pandapay account.', 'woocommerce-gateway-pandapay' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'publishable_key' => array(
			'title'       => __( 'Live Publishable Key', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'Get your API keys from your pandapay account.', 'woocommerce-gateway-pandapay' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'secret_key' => array(
			'title'       => __( 'Live Secret Key', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'Get your API keys from your pandapay account.', 'woocommerce-gateway-pandapay' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'statement_descriptor' => array(
			'title'       => __( 'Statement Descriptor', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'description' => __( 'Extra information about a charge. This will appear on your customer’s credit card statement.', 'woocommerce-gateway-pandapay' ),
			'default'     => '',
			'desc_tip'    => true,
		),
		'capture' => array(
			'title'       => __( 'Capture', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Capture charge immediately', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'Whether or not to immediately capture the charge. When unchecked, the charge issues an authorization and will need to be captured later. Uncaptured charges expire in 7 days.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'yes',
			'desc_tip'    => true,
		),
		'pandapay_checkout' => array(
			'title'       => __( 'Panda Pay Checkout', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Enable Panda Pay Checkout', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'If enabled, this option shows a "pay" button and modal credit card form on the checkout, instead of credit card fields directly on the page.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'pandapay_checkout_locale' => array(
			'title'       => __( 'Panda Pay Checkout locale', 'woocommerce-gateway-pandapay' ),
			'type'        => 'select',
			'class'       => 'wc-enhanced-select',
			'description' => __( 'Language to display in Panda Pay Checkout modal. Specify Auto to display Checkout in the user\'s preferred language, if available. English will be used by default.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'en',
			'desc_tip'    => true,
			'options'     => array(
				'auto' => __( 'Auto', 'woocommerce-gateway-pandapay' ),
				'zh'   => __( 'Simplified Chinese', 'woocommerce-gateway-pandapay' ),
				'da'   => __( 'Danish', 'woocommerce-gateway-pandapay' ),
				'nl'   => __( 'Dutch', 'woocommerce-gateway-pandapay' ),
				'en'   => __( 'English', 'woocommerce-gateway-pandapay' ),
				'fi'   => __( 'Finnish', 'woocommerce-gateway-pandapay' ),
				'fr'   => __( 'French', 'woocommerce-gateway-pandapay' ),
				'de'   => __( 'German', 'woocommerce-gateway-pandapay' ),
				'it'   => __( 'Italian', 'woocommerce-gateway-pandapay' ),
				'ja'   => __( 'Japanese', 'woocommerce-gateway-pandapay' ),
				'no'   => __( 'Norwegian', 'woocommerce-gateway-pandapay' ),
				'es'   => __( 'Spanish', 'woocommerce-gateway-pandapay' ),
				'sv'   => __( 'Swedish', 'woocommerce-gateway-pandapay' ),
			),
		),
		'pandapay_checkout_image' => array(
			'title'       => __( 'Panda Pay Checkout Image', 'woocommerce-gateway-pandapay' ),
			'description' => __( 'Optionally enter the URL to a 128x128px image of your brand or product. e.g. <code>https://yoursite.com/wp-content/uploads/2013/09/yourimage.jpg</code>', 'woocommerce-gateway-pandapay' ),
			'type'        => 'text',
			'default'     => '',
			'desc_tip'    => true,
		),
		'request_payment_api' => array(
			'title'       => __( 'Payment Request API', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Enable Payment Request API', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'If enabled, users will be able to pay using the Payment Request API if supported by the browser.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'saved_cards' => array(
			'title'       => __( 'Saved Cards', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Enable Payment via Saved Cards', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'If enabled, users will be able to pay with a saved card during checkout. Card details are saved on Panda Pay servers, not on your store.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
		'logging' => array(
			'title'       => __( 'Logging', 'woocommerce-gateway-pandapay' ),
			'label'       => __( 'Log debug messages', 'woocommerce-gateway-pandapay' ),
			'type'        => 'checkbox',
			'description' => __( 'Save debug messages to the WooCommerce System Status log.', 'woocommerce-gateway-pandapay' ),
			'default'     => 'no',
			'desc_tip'    => true,
		),
	)
);
